services:
  docs:
    image: voters_local_docs
    container_name: voters_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./voters:/app/voters:z
    ports:
      - '9000:9000'
    command: /start-docs
